=== nagygabi734/h194qsxmlGyak/XMLFeladatH194QS/XMLSchemaH194QS.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="root">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="alkalmazottak">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="alkalmazott" minOccurs="1"
								maxOccurs="1000">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="alkalmazottnev" type="xs:string" />
										<xs:element name="telefonszam" type="telefonTipus" />
										<xs:element name="lakcim">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="iranyitoszam"
														type="irányitoszamTipus" />
													<xs:element name="varos" type="xs:string" />
													<xs:element name="ut" type="xs:string" />
													<xs:element name="hazszam"
														type="xs:positiveInteger" />
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
									<xs:attribute name="alkalmazottid"
										type="xs:string" />
									<xs:attribute name="reszlegid" type="xs:string" />
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="apkapcsok">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="apkapcs" minOccurs="1"
								maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="munkaora" type="munkaoraTipus" />
									</xs:sequence>
									<xs:attribute name="alkalmazottid"
										type="xs:string" />
									<xs:attribute name="projektid" type="xs:string" />
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="cegek">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="ceg" minOccurs="1" maxOccurs="100">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="cegnev" type="xs:string" />
										<xs:element name="cegcim">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="iranyitoszam"
														type="irányitoszamTipus" />
													<xs:element name="varos" type="xs:string" />
													<xs:element name="ut" type="xs:string" />
													<xs:element name="hazszam"
														type="xs:positiveInteger" />
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
									<xs:attribute name="cegid" type="xs:string" />
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="ceg_tulajdonosok">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="ceg_tulajdonos" minOccurs="1"
								maxOccurs="5">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="tulajdonos" type="xs:string" />
									</xs:sequence>
									<xs:attribute name="cegid" type="xs:string" />
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="projektek">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="projekt" minOccurs="1"
								maxOccurs="10">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="projektnev" type="xs:string" />
										<xs:element name="projektfelelos" type="xs:string" />
										<xs:element name="hatarido" type="datumTipus" />
									</xs:sequence>
									<xs:attribute name="projektid" type="xs:string" />
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="reszlegek">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="reszleg" minOccurs="1"
								maxOccurs="25">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="reszlegnev" type="xs:string" />
										<xs:element name="telephely" type="xs:string" />
										<xs:element name="muszak" type="muszakTipus" />
									</xs:sequence>
									<xs:attribute name="reszlegid" type="xs:string" />
									<xs:attribute name="cegid" type="xs:string" />
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
		<xs:key name="Key_alkalmazott">
			<xs:selector xpath="alkalmazott"/>
			<xs:field xpath="@alkalmazottid"/>
		</xs:key> 
		<xs:key name="Key_ceg">
			<xs:selector xpath="ceg"/>
			<xs:field xpath="@cegid"/>
		</xs:key> 
		<xs:key name="Key_projekt">
			<xs:selector xpath="projekt"/>
			<xs:field xpath="@projektid"/>
		</xs:key> 
		<xs:key name="Key_reszleg">
			<xs:selector xpath="reszleg"/>
			<xs:field xpath="@reszlegid"/>
		</xs:key> 
		<xs:keyref name="FKey_ceg_tulajdonos_ceg" refer="Key_ceg">
			<xs:selector xpath="ceg_tulajdonos"/>
			<xs:field xpath="@cegid"/>
		</xs:keyref> 
		<xs:keyref name="FKey_reszleg_ceg" refer="Key_ceg">
			<xs:selector xpath="reszleg"/>
			<xs:field xpath="@cegid"/>
		</xs:keyref> 
		
		<xs:keyref name="FKey_alkalmazott_reszleg" refer="Key_reszleg">
			<xs:selector xpath="alkalmazott"/>
			<xs:field xpath="@reszlegid"/>
		</xs:keyref> 
		<xs:keyref name="FKey_APkapcs_alkalmazott" refer="Key_alkalmazott">
			<xs:selector xpath="apkapcs"/>
			<xs:field xpath="@alkalmazottid"/>
		</xs:keyref> 
		<xs:keyref name="FKey_APkapcs_projekt" refer="Key_projekt">
			<xs:selector xpath="apkapcs"/>
			<xs:field xpath="@projektid"/>
		</xs:keyref> 
	</xs:element>
	<xs:simpleType name="irányitoszamTipus">
		<xs:restriction base="xs:positiveInteger">
			<xs:minInclusive value="1000" />
			<xs:maxInclusive value="9999" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="munkaoraTipus">
		<xs:restriction base="xs:positiveInteger">
			<xs:minInclusive value="1" />
			<xs:maxInclusive value="200" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="muszakTipus">
		<xs:restriction base="xs:positiveInteger">
			<xs:minInclusive value="1" />
			<xs:maxInclusive value="3" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="telefonTipus">
		<xs:restriction base="xs:string">
			<xs:pattern value="[0]{1}[0-9]{2}[0]{1}[0-9]{7}" />
			<xs:pattern value="[+]{1}[0-9]{3}[0]{1}[0-9]{7}" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="datumTipus">
		<xs:restriction base="xs:string">

			<!-- 2000.5.1 ,2000.5.01 -->
			<xs:pattern
				value="[1-9]{1}[0-9]{3}[.]{1}[1-9]{1}[.]{1}[1-9]{1}" />
			<xs:pattern
				value="[1-9]{1}[0-9]{3}[.]{1}[1-9]{1}[.]{1}[1-2]{1}[0-9]{1}" />
			<xs:pattern
				value="[1-9]{1}[0-9]{3}[.]{1}[1-9]{1}[.]{1}[0]{1}[1-9]{1}" />

			<!-- 2000.10.2,2000.10.02 -->
			<xs:pattern
				value="[1-9]{1}[0-9]{3}[.]{1}[1]{1}[0-2]{1}[.]{1}[1-9]{1}" />
			<xs:pattern
				value="[1-9]{1}[0-9]{3}[.]{1}[1]{1}[0-2]{1}[.]{1}[1-2]{1}[0-9]{1}" />
			<xs:pattern
				value="[1-9]{1}[0-9]{3}[.]{1}[1]{1}[0-2]{1}[.]{1}[0]{1}[1-9]{1}" />

			<!-- 2000.05.1 ,2000.05.01 -->
			<xs:pattern
				value="[1-9]{1}[0-9]{3}[.]{1}[0]{1}[1-9]{1}[.]{1}[1-9]{1}" />
			<xs:pattern
				value="[1-9]{1}[0-9]{3}[.]{1}[0]{1}[1-9]{1}[.]{1}[1-2]{1}[0-9]{1}" />
			<xs:pattern
				value="[1-9]{1}[0-9]{3}[.]{1}[0]{1}[1-9]{1}[.]{1}[0]{1}[1-9]{1}" />

			<!-- január 31nap -->
			<xs:pattern
				value="[1-9]{1}[0-9]{3}[.]{1}[1]{1}[.]{1}[3]{1}[0-1]{1}" />
			<xs:pattern
				value="[1-9]{1}[0-9]{3}[.]{1}[0]{1}[1]{1}[.]{1}[3]{1}[0-1]{1}" />

			<!-- február 29nap -->

			<!-- március 31nap -->
			<xs:pattern
				value="[1-9]{1}[0-9]{3}[.]{1}[3]{1}[.]{1}[3]{1}[0-1]{1}" />
			<xs:pattern
				value="[1-9]{1}[0-9]{3}[.]{1}[0]{1}[3]{1}[.]{1}[3]{1}[0-1]{1}" />

			<!-- április 30nap -->
			<xs:pattern
				value="[1-9]{1}[0-9]{3}[.]{1}[4]{1}[.]{1}[3]{1}[0]{1}" />
			<xs:pattern
				value="[1-9]{1}[0-9]{3}[.]{1}[0]{1}[4]{1}[.]{1}[3]{1}[0]{1}" />

			<!-- május 31nap -->
			<xs:pattern
				value="[1-9]{1}[0-9]{3}[.]{1}[5]{1}[.]{1}[3]{1}[0-1]{1}" />
			<xs:pattern
				value="[1-9]{1}[0-9]{3}[.]{1}[0]{1}[5]{1}[.]{1}[3]{1}[0-1]{1}" />

			<!-- június 30nap -->
			<xs:pattern
				value="[1-9]{1}[0-9]{3}[.]{1}[6]{1}[.]{1}[3]{1}[0]{1}" />
			<xs:pattern
				value="[1-9]{1}[0-9]{3}[.]{1}[0]{1}[6]{1}[.]{1}[3]{1}[0]{1}" />

			<!-- július 31nap -->
			<xs:pattern
				value="[1-9]{1}[0-9]{3}[.]{1}[7]{1}[.]{1}[3]{1}[0-1]{1}" />
			<xs:pattern
				value="[1-9]{1}[0-9]{3}[.]{1}[0]{1}[7]{1}[.]{1}[3]{1}[0-1]{1}" />

			<!-- augusztus 31nap -->
			<xs:pattern
				value="[1-9]{1}[0-9]{3}[.]{1}[8]{1}[.]{1}[3]{1}[0-1]{1}" />
			<xs:pattern
				value="[1-9]{1}[0-9]{3}[.]{1}[0]{1}[8]{1}[.]{1}[3]{1}[0-1]{1}" />

			<!-- szeptember 30nap -->
			<xs:pattern
				value="[1-9]{1}[0-9]{3}[.]{1}[9]{1}[.]{1}[3]{1}[0]{1}" />
			<xs:pattern
				value="[1-9]{1}[0-9]{3}[.]{1}[0]{1}[9]{1}[.]{1}[3]{1}[0]{1}" />

			<!-- október 31nap -->
			<xs:pattern
				value="[1-9]{1}[0-9]{3}[.]{1}[1]{1}[0]{1}[.]{1}[3]{1}[0-1]{1}" />

			<!-- november 30nap -->
			<xs:pattern
				value="[1-9]{1}[0-9]{3}[.]{1}[1]{1}[1]{1}[.]{1}[3]{1}[0]{1}" />

			<!-- december 31nap -->
			<xs:pattern
				value="[1-9]{1}[0-9]{3}[.]{1}[1]{1}[2]{1}[.]{1}[3]{1}[0-1]{1}" />

		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== nagygabi734/h194qsxmlGyak/XMLFeladatH194QS/XMLH194QS.xml
<?xml version="1.0" encoding="UTF-8"?>
<root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="XMLSchemaH194QS.xsd">
	<alkalmazottak>
		<alkalmazott alkalmazottid="a1" reszlegid="r1">
			<alkalmazottnev>Koszos Károly</alkalmazottnev>
			<telefonszam>06302658471</telefonszam>
			<lakcim>
				<iranyitoszam>4515</iranyitoszam>
				<varos>Nincslaki</varos>
				<ut>Kimondhatatlan</ut>
				<hazszam>123</hazszam>
			</lakcim>
		</alkalmazott>
		<alkalmazott alkalmazottid="a2" reszlegid="r1">
			<alkalmazottnev>Sáros Sándor</alkalmazottnev>
			<telefonszam>+36202658471</telefonszam>
			<lakcim>
				<iranyitoszam>4500</iranyitoszam>
				<varos>Vanlaki</varos>
				<ut>Kimondható</ut>
				<hazszam>321</hazszam>
			</lakcim>
		</alkalmazott>
		<alkalmazott alkalmazottid="a3" reszlegid="r2">
			<alkalmazottnev>Sima Sándor</alkalmazottnev>
			<telefonszam>06302648957</telefonszam>
			<lakcim>
				<iranyitoszam>4517</iranyitoszam>
				<varos>Lehetlaki</varos>
				<ut>Nemlaki</ut>
				<hazszam>258</hazszam>
			</lakcim>
		</alkalmazott>
		<alkalmazott alkalmazottid="a4" reszlegid="r2">
			<alkalmazottnev>Kormos Károly</alkalmazottnev>
			<telefonszam>06702658957</telefonszam>
			<lakcim>
				<iranyitoszam>2875</iranyitoszam>
				<varos>Bűnös</varos>
				<ut>Börtön</ut>
				<hazszam>15</hazszam>
			</lakcim>
		</alkalmazott>
	</alkalmazottak>
	<apkapcsok>
		<apkapcs alkalmazottid="a1" projektid="p1">
			<munkaora>15</munkaora>
		</apkapcs>
		<apkapcs alkalmazottid="a2" projektid="p1">
			<munkaora>50</munkaora>
		</apkapcs>
		<apkapcs alkalmazottid="a2" projektid="p2">
			<munkaora>50</munkaora>
		</apkapcs>
		<apkapcs alkalmazottid="a3" projektid="p1">
			<munkaora>157</munkaora>
		</apkapcs>
		<apkapcs alkalmazottid="a4" projektid="p2">
			<munkaora>168</munkaora>
		</apkapcs>
	</apkapcsok>
	<cegek>
		<ceg cegid="c1">
			<cegnev>Alma Kft.</cegnev>
			<cegcim>
				<iranyitoszam>8888</iranyitoszam>
				<varos>Miskolc</varos>
				<ut>Nemtudom</ut>
				<hazszam>154</hazszam>
			</cegcim>
		</ceg>
		<ceg cegid="c2">
			<cegnev>Körte Kft.</cegnev>
			<cegcim>
				<iranyitoszam>1248</iranyitoszam>
				<varos>Budapest</varos>
				<ut>Kínos</ut>
				<hazszam>258</hazszam>
			</cegcim>
		</ceg>
	</cegek>s
	<ceg_tulajdonosok>
		<ceg_tulajdonos cegid="c1">
			<tulajdonos>Piros Alma</tulajdonos>
		</ceg_tulajdonos>
		<ceg_tulajdonos cegid="c1">
			<tulajdonos>Zöld Alma</tulajdonos>
		</ceg_tulajdonos>
		<ceg_tulajdonos cegid="c2">
			<tulajdonos>Zöld Körte</tulajdonos>
		</ceg_tulajdonos>
	</ceg_tulajdonosok>
	<projektek>
		<projekt projektid="p1">
			<projektnev>Kettő forint</projektnev>
			<projektfelelos>Koszos Károly</projektfelelos>
			<hatarido>2020.10.15</hatarido>
		</projekt>
		<projekt projektid="p2">
			<projektnev>Három forint</projektnev>
			<projektfelelos>Sáros Sándor</projektfelelos>
			<hatarido>2025.01.24</hatarido>
		</projekt>
	</projektek>
	<reszlegek>
		<reszleg reszlegid="r1" cegid="c1">
			<reszlegnev>Préselő</reszlegnev>
			<telephely>Miskolc</telephely>
			<muszak>3</muszak>
		</reszleg>
		<reszleg reszlegid="r2" cegid="c2">
			<reszlegnev>Préselő</reszlegnev>
			<telephely>Budapest</telephely>
			<muszak>1</muszak>
		</reszleg>
		<reszleg reszlegid="r3" cegid="c2">
			<reszlegnev>Préselő</reszlegnev>
			<telephely>Miskolc</telephely>
			<muszak>2</muszak>
		</reszleg>
	</reszlegek>
</root>
